# Generated by Django 6.1 on 2026-08-19 15:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="FilmStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("iso", models.PositiveSmallIntegerField()),
                ("format", models.CharField(max_length=255)),
                ("color_type", models.CharField(max_length=255)),
                ("frames", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cameras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "camera_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cameras",
                        to="api.cameramodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stored", "Stored"),
                            ("loaded", "Loaded"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                            ("developed", "Developed"),
                            ("scanned", "Scanned"),
                        ],
                        default="stored",
                        max_length=255,
                    ),
                ),
                ("frames_shot", models.PositiveSmallIntegerField(default=0)),
                ("expiration_date", models.DateField()),
                ("date_bought", models.DateField(blank=True, null=True)),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_loaded", models.DateField(blank=True, null=True)),
                ("date_finished", models.DateField(blank=True, null=True)),
                ("date_developed", models.DateField(blank=True, null=True)),
                ("date_scanned", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rolls",
                        to="api.camera",
                    ),
                ),
                (
                    "film_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolls",
                        to="api.filmstock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
