# Generated by Django 6.1 on 2026-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cameramodel_filmstock_camera_roll"),
    ]

    operations = [
        migrations.AddField(
            model_name="roll",
            name="shot_iso",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
