# Generated by Django 6.1 on 2026-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_roll_shot_iso"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameramodel",
            name="has_prewind",
            field=models.BooleanField(default=False),
        ),
    ]
