# Generated by Django 6.1 on 2026-09-08 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cameramodel_has_prewind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roll",
            name="frames_shot",
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("exposed", "Exposed"), ("blank", "Blank")],
                        default="exposed",
                        max_length=255,
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frames",
                        to="api.camera",
                    ),
                ),
                (
                    "roll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="api.roll",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roll", "position"),
                        name="unique_frame_position_per_roll",
                    )
                ],
            },
        ),
    ]
