/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["api_routers_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login View */
        post: operations["api_routers_auth_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["api_routers_auth_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["api_routers_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera-models/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Camera Models */
        get: operations["api_routers_camera_models_list_camera_models"];
        put?: never;
        /** Create Camera Model */
        post: operations["api_routers_camera_models_create_camera_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/camera-models/{camera_model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Model */
        get: operations["api_routers_camera_models_get_camera_model"];
        /** Update Camera Model */
        put: operations["api_routers_camera_models_update_camera_model"];
        post?: never;
        /** Delete Camera Model */
        delete: operations["api_routers_camera_models_delete_camera_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["api_routers_cameras_list_cameras"];
        put?: never;
        /** Create Camera */
        post: operations["api_routers_cameras_create_camera"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Model */
        get: operations["api_routers_cameras_get_camera_model"];
        /** Update Camera Model */
        put: operations["api_routers_cameras_update_camera_model"];
        post?: never;
        /** Delete Camera Model */
        delete: operations["api_routers_cameras_delete_camera_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/film-stocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Film Stocks */
        get: operations["api_routers_film_stocks_list_film_stocks"];
        put?: never;
        /** Create Film Stock */
        post: operations["api_routers_film_stocks_create_film_stock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/film-stocks/{film_stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Film Stock Model */
        get: operations["api_routers_film_stocks_get_film_stock_model"];
        /** Update Film Stock Model */
        put: operations["api_routers_film_stocks_update_film_stock_model"];
        post?: never;
        /** Delete Film Stock Model */
        delete: operations["api_routers_film_stocks_delete_film_stock_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rolls/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rolls */
        get: operations["api_routers_rolls_list_rolls"];
        put?: never;
        /** Create Roll */
        post: operations["api_routers_rolls_create_roll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rolls/{roll_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roll Model */
        get: operations["api_routers_rolls_get_roll_model"];
        /** Update Roll Model */
        put: operations["api_routers_rolls_update_roll_model"];
        post?: never;
        /** Delete Roll Model */
        delete: operations["api_routers_rolls_delete_roll_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id?: string | null;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            username: string;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** CameraModelOut */
        CameraModelOut: {
            /** Id */
            id?: string | null;
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Format */
            format: string;
        };
        /** CameraModelIn */
        CameraModelIn: {
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Format */
            format: string;
        };
        /** CameraOut */
        CameraOut: {
            camera_model: components["schemas"]["CameraModelOut"];
            /** Id */
            id?: string | null;
        };
        /** CameraIn */
        CameraIn: {
            /**
             * Camera Model Id
             * Format: uuid
             */
            camera_model_id: string;
        };
        /** FilmStockOut */
        FilmStockOut: {
            /** Id */
            id?: string | null;
            /** Brand */
            brand: string;
            /** Name */
            name: string;
            /** Iso */
            iso: number;
            /** Format */
            format: string;
            /** Color Type */
            color_type: string;
            /** Frames */
            frames: number;
        };
        /** FilmStockIn */
        FilmStockIn: {
            /** Brand */
            brand: string;
            /** Name */
            name: string;
            /** Iso */
            iso: number;
            /** Format */
            format: string;
            /** Color Type */
            color_type: string;
            /** Frames */
            frames: number;
        };
        /** RollOut */
        RollOut: {
            film_stock: components["schemas"]["FilmStockOut"];
            camera: components["schemas"]["CameraOut"] | null;
            /** Is In Progress */
            is_in_progress: boolean;
            /** Id */
            id?: string | null;
            /**
             * Status
             * @default stored
             */
            status: string;
            /**
             * Frames Shot
             * @default 0
             */
            frames_shot: number;
            /**
             * Expiration Date
             * Format: date
             */
            expiration_date: string;
            /** Date Bought */
            date_bought?: string | null;
            /** Date Started */
            date_started?: string | null;
            /** Date Loaded */
            date_loaded?: string | null;
            /** Date Finished */
            date_finished?: string | null;
            /** Date Developed */
            date_developed?: string | null;
            /** Date Scanned */
            date_scanned?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** RollIn */
        RollIn: {
            /**
             * Film Stock Id
             * Format: uuid
             */
            film_stock_id: string;
            /** Camera Id */
            camera_id?: string | null;
            /** @default stored */
            status: components["schemas"]["Status"];
            /**
             * Frames Shot
             * @default 0
             */
            frames_shot: number;
            /**
             * Expiration Date
             * Format: date
             */
            expiration_date: string;
            /** Date Bought */
            date_bought?: string | null;
            /** Date Started */
            date_started?: string | null;
            /** Date Loaded */
            date_loaded?: string | null;
            /** Date Finished */
            date_finished?: string | null;
            /** Date Developed */
            date_developed?: string | null;
            /** Date Scanned */
            date_scanned?: string | null;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "stored" | "loaded" | "started" | "finished" | "developed" | "scanned";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_routers_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    api_routers_auth_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    api_routers_auth_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    api_routers_camera_models_list_camera_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraModelOut"][];
                };
            };
        };
    };
    api_routers_camera_models_create_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraModelIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraModelOut"];
                };
            };
        };
    };
    api_routers_camera_models_get_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraModelOut"];
                };
            };
        };
    };
    api_routers_camera_models_update_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraModelIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraModelOut"];
                };
            };
        };
    };
    api_routers_camera_models_delete_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_cameras_list_cameras: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"][];
                };
            };
        };
    };
    api_routers_cameras_create_camera: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
        };
    };
    api_routers_cameras_get_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
        };
    };
    api_routers_cameras_update_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
        };
    };
    api_routers_cameras_delete_camera_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_film_stocks_list_film_stocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmStockOut"][];
                };
            };
        };
    };
    api_routers_film_stocks_create_film_stock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilmStockIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmStockOut"];
                };
            };
        };
    };
    api_routers_film_stocks_get_film_stock_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                film_stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmStockOut"];
                };
            };
        };
    };
    api_routers_film_stocks_update_film_stock_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                film_stock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FilmStockIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilmStockOut"];
                };
            };
        };
    };
    api_routers_film_stocks_delete_film_stock_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                film_stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_routers_rolls_list_rolls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollOut"][];
                };
            };
        };
    };
    api_routers_rolls_create_roll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollOut"];
                };
            };
        };
    };
    api_routers_rolls_get_roll_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roll_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollOut"];
                };
            };
        };
    };
    api_routers_rolls_update_roll_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roll_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollOut"];
                };
            };
        };
    };
    api_routers_rolls_delete_roll_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roll_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
